name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      sample: ${{ steps.filter.outputs.sample }}
      slack: ${{ steps.filter.outputs.slack }}
      version-bump: ${{ steps.filter.outputs.version-bump }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            version-bump:
              - 'version-bump/**'

  compile-version-bump:
    needs: check-changes
    if: needs.check-changes.outputs.version-bump == 'true'
    uses: ./.github/workflows/build-version-bump.yml

  build:
    runs-on: ubuntu-latest
    needs:
      - check-changes
      - compile-version-bump
    if: always()
    steps:
      - name: Check status
        env:
          VERSION_BUMP_CHANGED: ${{ needs.check-changes.outputs.version-bump }}
          VERSION_BUMP_RESULT: ${{ needs.compile-version-bump.result }}
        run: |
          if [[ "$VERSION_BUMP_CHANGED" == "false" ]]; then
            echo "No relevant changes detected"
            exit 0
          fi
          if [[ "$VERSION_BUMP_RESULT" == "failure" ]]; then
            echo "A compile job failed"
            exit 1
          fi
          echo "Build succeeded"
