name: Build version-bump

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - version-bump/

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: version-bump
        run: npm ci

      - name: Type check
        working-directory: version-bump
        run: npm run type-check

      - name: Test
        working-directory: version-bump
        run: npm run test
